<?php

/**
 * BaseFridge
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $name
 * @property varchar $brand
 * @property integer $capacity
 * @property Doctrine_Collection $Items
 * 
 * @method text                getName()     Returns the current record's "name" value
 * @method varchar             getBrand()    Returns the current record's "brand" value
 * @method integer             getCapaCity() Returns the current record's "capacity" value
 * @method Doctrine_Collection getItems()    Returns the current record's "Items" collection
 * @method Fridge              setName()     Sets the current record's "name" value
 * @method Fridge              setBrand()    Sets the current record's "brand" value
 * @method Fridge              setCapaCity() Sets the current record's "capacity" value
 * @method Fridge              setItems()    Sets the current record's "Items" collection
 * 
 * @package    what2cook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFridge extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fridge');
        $this->hasColumn('name', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('brand', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('capacity', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FridgeItem as Items', array(
             'local' => 'id',
             'foreign' => 'idFridge'));
    }
}