<?php

/**
 * BaseIngredient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $name
 * @property integer $amount
 * @property enum $unit
 * @property integer $idRecipe
 * @property Recipe $Recipe
 * 
 * @method text       getName()     Returns the current record's "name" value
 * @method integer    getAmount()   Returns the current record's "amount" value
 * @method enum       getUnit()     Returns the current record's "unit" value
 * @method integer    getIdRecIpe() Returns the current record's "idRecipe" value
 * @method Recipe     getRecipe()   Returns the current record's "Recipe" value
 * @method Ingredient setName()     Sets the current record's "name" value
 * @method Ingredient setAmount()   Sets the current record's "amount" value
 * @method Ingredient setUnit()     Sets the current record's "unit" value
 * @method Ingredient setIdRecIpe() Sets the current record's "idRecipe" value
 * @method Ingredient setRecipe()   Sets the current record's "Recipe" value
 * 
 * @package    what2cook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIngredient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ingredient');
        $this->hasColumn('name', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('amount', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('unit', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'of',
              1 => 'grams',
              2 => 'ml',
              3 => 'slices',
             ),
             ));
        $this->hasColumn('idRecipe', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Recipe', array(
             'local' => 'idRecipe',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}