<?php

/**
 * BaseRecipe
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $name
 * @property integer $preptime
 * @property integer $cooktime
 * @property integer $readytime
 * @property text $directions
 * @property Doctrine_Collection $Ingredients
 * 
 * @method text                getName()        Returns the current record's "name" value
 * @method integer             getPrePtime()    Returns the current record's "preptime" value
 * @method integer             getCooktime()    Returns the current record's "cooktime" value
 * @method integer             getReadytime()   Returns the current record's "readytime" value
 * @method text                getDirections()  Returns the current record's "directions" value
 * @method Doctrine_Collection getIngredients() Returns the current record's "Ingredients" collection
 * @method Recipe              setName()        Sets the current record's "name" value
 * @method Recipe              setPrePtime()    Sets the current record's "preptime" value
 * @method Recipe              setCooktime()    Sets the current record's "cooktime" value
 * @method Recipe              setReadytime()   Sets the current record's "readytime" value
 * @method Recipe              setDirections()  Sets the current record's "directions" value
 * @method Recipe              setIngredients() Sets the current record's "Ingredients" collection
 * 
 * @package    what2cook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecipe extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('recipe');
        $this->hasColumn('name', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('preptime', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('cooktime', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('readytime', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('directions', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Ingredient as Ingredients', array(
             'local' => 'id',
             'foreign' => 'idRecipe'));
    }
}