<?php

/**
 * BaseFridgeItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $name
 * @property integer $amount
 * @property enum $unit
 * @property timestamp $useby
 * @property integer $idFridge
 * @property Fridge $Fridge
 * 
 * @method text       getName()     Returns the current record's "name" value
 * @method integer    getAmount()   Returns the current record's "amount" value
 * @method enum       getUnit()     Returns the current record's "unit" value
 * @method timestamp  getUseby()    Returns the current record's "useby" value
 * @method integer    getIdFrIdge() Returns the current record's "idFridge" value
 * @method Fridge     getFridge()   Returns the current record's "Fridge" value
 * @method FridgeItem setName()     Sets the current record's "name" value
 * @method FridgeItem setAmount()   Sets the current record's "amount" value
 * @method FridgeItem setUnit()     Sets the current record's "unit" value
 * @method FridgeItem setUseby()    Sets the current record's "useby" value
 * @method FridgeItem setIdFrIdge() Sets the current record's "idFridge" value
 * @method FridgeItem setFridge()   Sets the current record's "Fridge" value
 * 
 * @package    what2cook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFridgeItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fridge_item');
        $this->hasColumn('name', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('amount', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('unit', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'of',
              1 => 'grams',
              2 => 'ml',
              3 => 'slices',
             ),
             ));
        $this->hasColumn('useby', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('idFridge', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Fridge', array(
             'local' => 'idFridge',
             'foreign' => 'id'));
    }
}