<?php

/**
 * FridgeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FridgeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FridgeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Fridge');
    }
}