<?php

/**
 * Fridge
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    what2cook
 * @subpackage model
 * @author     Fan Deng
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Fridge extends BaseFridge
{
  private $recipes = array();

  /**
	* Fridge::loadItems()
	*
	* load items form array
	*
	* @param array $items
	* @author Fan Deng
	*/
  public function loadItems(array $items) {
    foreach ($items as $item) {
      $fridgeItem = new FridgeItem();
      $fridgeItem->initialize($item);
      $this->Items[] = $fridgeItem;
    }
  }

  /**
	* Fridge::loadItemsFromFile()
	*
	* load items from csv file
	*
	* @param unknown $filename
	* @author Fan Deng
	*/
  public function loadItemsFromFile($filename) {
    $items = array();
    if (($handle = fopen($filename, 'r')) !== FALSE) {
      while (($row = fgetcsv($handle, 1000, ',')) !== FALSE) 	{
        $items[] = $row;
      }
      fclose($handle);
    }
    $this->loadItems($items);
  }

  /**
	* Fridge::findIngredient()
	*
	* search Fridge items for given ingredient name, amount and unit
	*
	* @param unknown $name
	* @param unknown $amount
	* @param unknown $unit
	* @return string or boolean, a date string of useBy of hit, or false if miss or item unacceptable
	* @author Fan Deng
	*/
  public function findIngredient($name, $amount, $unit) {
    foreach ($this->Items as $item) {
      if ($item->getName() != $name) continue;
      if ($item->getAmount() < $amount) continue;
      if ($item->getUnit() != $unit) continue;
      if ($item->isExpired()) continue;

      return $item->getUseBy();
    }
    return false;
  }

  /**
	* Fridge::searchRecipe()
	*
	* search items for a match recipe
	*
	* @param array $recipes
	* @throws sfException
	* @return Ambigous <boolean, Recipe>
	* @author Fan Deng
	*/
  public function searchRecipe(array $recipes = array()) {
    $found = false;
    $recipe_ts = 0;

    foreach ($recipes as $recipe) {
      if (!$recipe instanceof Recipe)
        throw new sfException('Invalid type, must search within Recipes!');

      $ts = 0;
      foreach ($recipe->getIngredients() as $ingredient) {
        $useby = $this->findIngredient($ingredient->getName(), $ingredient->getAmount(), $ingredient->getUnit());
        if (!$useby) continue 2; //once one ingredient not found, try next recipe

        list($d, $m, $y) = explode('/', $useby);
        $_ts = strtotime(sprintf('%d-%d-%d', $y, $m, $d));
        if (!$ts || $_ts < $ts) $ts = $_ts; //get closer use-by timestamp
      }

      if (!$recipe_ts || $ts < $recipe_ts) {
        $recipe_ts = $ts;
        $found = $recipe;
      }
    }

    return $found;
  }
}
