<?php

/**
 * FridgeItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    what2cook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class FridgeItem extends BaseFridgeItem
{
  public function initialize(array $values) {
    if (count($values) != 4 || count(array_diff(array_keys($values), array(0, 1, 2, 3))))
      throw new sfException('Invalid init values!');

    $this->setName($values[0]);
    $this->setAmount($values[1]);
    $this->setUnit($values[2]);
    $this->setUseBy($values[3]);
  }

  public function isExpired() {
    list($d, $m, $y) = explode('/', $this->getUseBy());

    return strtotime(sprintf('%d-%d-%d', $y, $m, $d)) < time();
  }
}
