<?php

/**
 * Ingredient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    what2cook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ingredient extends BaseIngredient
{
  public function initialize($values) {
    if (count($values) != 3 || count(array_diff(array_keys($values), array('item', 'amount', 'unit'))))
      throw new sfException('Invalid init values!');

    $this->setName($values['item']);
    $this->setAmount($values['amount']);
    $this->setUnit($values['unit']);
  }
}
