<?php

/**
 * IngredientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IngredientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IngredientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ingredient');
    }
}