<?php

/**
 * Ingredient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    what2cook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Ingredient extends BaseIngredient
{
  public function initialize($values) {
    $this->setName($values['item']);
    $this->setAmount($values['amount']);
    $this->setUnit($values['unit']);
  }

  public function __toString() {
    return sprintf("\t\tItem: %s, Amount: %d, Unit: %s\n", $this->getName(), $this->getAmount(), $this->getUnit());
  }
}
