<?php

/**
 * Recipe
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    what2cook
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Recipe extends BaseRecipe
{
  public function loadIngredients(array $values) {
    foreach($values as $value) {
      $ingredient = new Ingredient();
      $ingredient->initialize($value);
      $this->Ingredients[] = $ingredient;
    }
  }

  public function __toString() {
    $string = sprintf("\tName: %s\n\tIngredients:\n", $this->getName());

    foreach ($this->getIngredients() as $ingredient) {
      $string .= (string) $ingredient;
    }

    return $string;
  }
}
