<?php

/**
 * RecipeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RecipeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RecipeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Recipe');
    }
}